server:
  port: 9094

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 45
    port: 9091
    metadata-map:
      server.servlet.context-path: ${server.servlet.context-path}
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user:
        name: "user"         #These two are needed so that the server
        password: "password" #can access the protected client endpoints
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

spring:
  application:
    name: admin-service
  profiles:
    active:
      - secure
  boot:
    admin:
      context-path: /admin
      ui:
        title: Mixed Salad Admin
      notify:
        telegram:
          enabled: true
          auth-token: 798219666:AAHjjOXnUdV1yNsw_HNUfUlN4hu2A9AoxAo
          chat-id: -377205524
          parse-mode: 'HTML'
          message: "<strong>#{instance.registration.name}</strong>/#{instance.id} is <strong>#{event.statusInfo.status}</strong>"
  security:
    user:
      name: "user"
      password: "password"
  zipkin:
    base-url: http://localhost:9095/

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: logs/admin-service.log
