server:
  port: 9094

eureka:
  instance:
    hostname: localhost
    port: 9091
    metadata-map:
      user.name: "user"         #These two are needed so that the server
      user.password: "password" #can access the protected client endpoints
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active:
      - secure
  boot:
    admin:
      context-path: /admin
      ui:
        title: Mixed Salad Admin
  security:
    user:
      name: "user"
      password: "password"

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
