server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: banco-central-service.log

spring:
  application:
    name: banco-central-service
  cloud:
    boot:
      admin:
        client:
          url: http://localhost:9094/admin
          # username: "user"
          # password: "password" 
  datasource:
    hikari:
      maximum-pool-size: 25
    url: jdbc:h2:file:./bancocentral-app;DB_CLOSE_ON_EXIT=TRUE
    platform: h2
    username: bancocentral
    password: bancocentral
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        type: trace
        jdbc:
          time_zone: UTC-3
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    mongo:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
authserver:
  hostname: http://localhost:9092/oauth
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user