server:
  port: 9091

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9091/eureka/

eureka:
  datacenter: MixedSalad
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
spring:
  cloud:    
    boot:
      admin:
        client:
          url: http://localhost:9094/admin
          username: "user"
          password: "password"
  zipkin:
    base-url: http://localhost:9095/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: logs/discovery-service.log