server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: gateway-service.log

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/(?<path>.*), /$\{path}
        - id: banco-central-service
          uri: lb://banco-central-service
          predicates:
            - Path=/bc/**
          filters:
            - RewritePath=/bc/(?<path>.*), /$\{path}