server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: gateway-service.log

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/(?<path>.*), /$\{path}
        - id: banco-central-service
          uri: lb://banco-central-service
          predicates:
            - Path=/bc/**
          filters:
            - RewritePath=/bc/(?<path>.*), /$\{path}