server:
  port: 9095
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka/
  boot:
    admin:
      client:
        url: http://admin-service:9094/admin
        username: "user"
        password: "password"
spring:
  profiles:
    active: dev

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: logs/zipkin-service.log